version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - "5501:3306"
    expose:
      - "5501"
    environment:
      MYSQL_DATABASE: oos
      MYSQL_ROOT_PASSWORD: 1234
    platform: linux/amd64  # mac에서 compose 할 경우 주석 해제 한 후 사용할 것